# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias vim="nvim"

alias lg='lazygit'

alias ld='lazydocker'

alias dbui='vim +DBUI'

alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"

eval "$(zoxide init zsh)"

alias cd="z"

alias fs='rg --line-number --no-heading . | fzf --ansi --delimiter : --preview "bat --color=always --highlight-line {2} {1}" --preview-window=right:50% | head -1 | while IFS=":" read -r file line rest; do nvim "+$line" "$file"; done'

alias ff='fzf --preview "bat --color=always {}" --preview-window=right:50% | head -1 | xargs -I {} nvim "{}"'

export JAVA_HOME="/opt/homebrew/opt/openjdk@17"
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/etiennepautet/.lmstudio/bin"
# End of LM Studio CLI section

export PATH="/Applications/Wireshark.app/Contents/MacOS:$PATH"

export PATH=$PATH:$HOME/go/bin
