tap "jesseduffield/lazygit"
tap "nikitabobko/tap"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Cross-platform make
brew "cmake"
# Console Matrix
brew "cmatrix"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Go Language's command-line interface for database migrations
brew "goose"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Network logon cracker which supports many services
brew "hydra"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Run a Kubernetes cluster locally
brew "minikube"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Utility for managing network connections
brew "netcat"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Port scanning utility for large networks
brew "nmap"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# Development kit for the Java programming language
brew "openjdk"
# Development kit for the Java programming language
brew "openjdk@17"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Object-relational database system
brew "postgresql@14"
# Theme for zsh
brew "powerlevel10k"
# SVG rendering tool and library
brew "resvg"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Launcher to analyze a project with SonarQube
brew "sonar-scanner"
# Generate type safe Go from SQL
brew "sqlc"
# Penetration testing for SQL injection and database servers
brew "sqlmap"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Parser generator tool
brew "tree-sitter-cli"
# Command-line tool for Vapor (Server-side Swift web framework)
brew "vapor"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Display management tool
cask "betterdisplay"
# Terminal emulator mimicking the old cathode display
cask "cool-retro-term"
cask "font-meslo-lg-nerd-font"
cask "font-symbols-only-nerd-font"
# Media system
cask "jellyfin"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
go "github.com/swaggo/swag/cmd/swag"
npm "@angular/cli"
npm "typescript"
